[project]
name = "sale-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.5",
    "djlint>=1.36.4",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
]
