# Generated by Django 5.2.5 on 2025-09-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_profile_avatar_profile_created_at_profile_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
