# Generated by Django 5.2.5 on 2025-09-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "permissions": [
                    ("can_access_profile_admin", "Pode acessar o site do perfil")
                ]
            },
        ),
    ]
