# Generated by Django 5.2.5 on 2025-09-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_post_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-published_at"],
                "permissions": [
                    ("can_access_profile_admin", "Pode acessar o site do perfil")
                ],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blue", "Azull"),
                    ("red", "Vermelho"),
                    ("yellow", "Amarelo"),
                    ("green", "Verde"),
                    ("purple", "Roxo"),
                    ("pink", "Rosa"),
                    ("indigo", "Indigo"),
                    ("gray", "Cinza"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
